In [2]:
#To install the Pandas - python library
!pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.4-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yuvaraj.r\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\yuvaraj.r\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.5 MB 8.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.9/11.5 MB 8.0 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.5 MB 7.3 MB/s eta 0:00:02
   -------------------- ------------------- 5.8/11.5 MB 7.3 MB/s eta 0:00:01
   ------------------------- -------------- 7.3/11.5 MB 7.4 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 7.0 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 6.8 MB/s eta 0:00:00
Downloading numpy-2.2.4-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 5.8 MB/s eta 0:00:02
   ----- ---------------------------------- 1.8/12.6 MB 4.1 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 5.1 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.6 MB 4.3 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.9 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.6 MB 4.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 4.0 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 4.1 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.6 MB 4.1 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 4.3 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 4.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 4.3 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.3 MB/s eta 0:00:00
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.4 pandas-2.2.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
#To install the pandas - python library
#Pandas - For data manipulation & analysis.
import pandas as PD

In [5]:
dataSet = PD.read_csv("Salary_Data.csv")

In [6]:
dataSet

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
inputVal = dataSet[["YearsExperience"]]
inputVal

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [8]:
outputVal = dataSet[["Salary"]]
outputVal

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [11]:
#To install the scikit-learn - python library
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\yuvaraj.r\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.4)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 950.7 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/11.1 MB 1.4 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/11.1 MB 1.9 MB/s eta 0:00:06
   ------- -------------------------------- 2.1/11.1 MB 2.2 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.1 MB 2.4 MB/s eta 0:00:04
   ---------- ----------------------------- 2.9/11.1 MB 2.0 MB/s eta 0:00:05
   ------------ --------------------------- 3.4/11.1 MB 2.1 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.1 MB 2.1 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.1 MB 2.1 MB/s eta 0:00:04
   ------------- -------------------------- 3.7/11.1 MB 2.1 MB/s eta 0:00:04
   -------------- ------------------------- 3.9/11.1 MB 1.6 MB/s eta 0:00:05
   --------------- ------------------------ 4.2/11.1 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 4.5/11.1 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.2/11.1 MB 1.7 MB/s eta 0:00:04
   -------------------- ------------------- 5.8/11.1 MB 1.8 MB/s eta 0:00:04
   ---------------------- ----------------- 6.3/11.1 MB 1.8 MB/s eta 0:00:03
   ------------------------ --------------- 6.8/11.1 MB 1.8 MB/s eta 0:00:03
   -------------------------- ------------- 7.3/11.1 MB 1.9 MB/s eta 0:00:02
   --------------------------- ------------ 7.6/11.1 MB 1.9 MB/s eta 0:00:02
   ------------------------------ --------- 8.4/11.1 MB 1.9 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.1 MB 1.9 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/11.1 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.1 MB 1.9 MB/s eta 0:00:01
   ------------------------------------ --- 10.2/11.1 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 10.7/11.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 1.9 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
    --------------------------------------- 0.5/41.0 MB 2.3 MB/s eta 0:00:18
    --------------------------------------- 0.8/41.0 MB 2.1 MB/s eta 0:00:20
   - -------------------------------------- 1.0/41.0 MB 1.8 MB/s eta 0:00:23
   - -------------------------------------- 1.8/41.0 MB 2.4 MB/s eta 0:00:17
   -- ------------------------------------- 2.6/41.0 MB 2.5 MB/s eta 0:00:16
   --- ------------------------------------ 3.4/41.0 MB 2.9 MB/s eta 0:00:13
   ---- ----------------------------------- 4.5/41.0 MB 3.1 MB/s eta 0:00:12
   ----- ---------------------------------- 5.2/41.0 MB 3.3 MB/s eta 0:00:11
   ----- ---------------------------------- 5.8/41.0 MB 3.4 MB/s eta 0:00:11
   ----- ---------------------------------- 5.8/41.0 MB 3.4 MB/s eta 0:00:11
   ----- ---------------------------------- 6.0/41.0 MB 2.8 MB/s eta 0:00:13
   ------ --------------------------------- 6.6/41.0 MB 2.7 MB/s eta 0:00:13
   ------- -------------------------------- 7.3/41.0 MB 2.7 MB/s eta 0:00:13
   ------- -------------------------------- 7.9/41.0 MB 2.7 MB/s eta 0:00:13
   ------- -------------------------------- 7.9/41.0 MB 2.7 MB/s eta 0:00:13
   -------- ------------------------------- 8.4/41.0 MB 2.6 MB/s eta 0:00:13
   -------- ------------------------------- 9.2/41.0 MB 2.6 MB/s eta 0:00:13
   --------- ------------------------------ 10.0/41.0 MB 2.7 MB/s eta 0:00:12
   --------- ------------------------------ 10.2/41.0 MB 2.6 MB/s eta 0:00:12
   ---------- ----------------------------- 10.5/41.0 MB 2.5 MB/s eta 0:00:13
   ---------- ----------------------------- 10.7/41.0 MB 2.5 MB/s eta 0:00:13
   ----------- ---------------------------- 11.5/41.0 MB 2.5 MB/s eta 0:00:12
   ----------- ---------------------------- 12.1/41.0 MB 2.5 MB/s eta 0:00:12
   ------------ --------------------------- 12.6/41.0 MB 2.5 MB/s eta 0:00:12
   ------------ --------------------------- 12.8/41.0 MB 2.5 MB/s eta 0:00:12
   ------------ --------------------------- 13.1/41.0 MB 2.4 MB/s eta 0:00:12
   ------------- -------------------------- 13.9/41.0 MB 2.5 MB/s eta 0:00:12
   ------------- -------------------------- 14.2/41.0 MB 2.5 MB/s eta 0:00:11
   -------------- ------------------------- 14.7/41.0 MB 2.4 MB/s eta 0:00:11
   -------------- ------------------------- 14.7/41.0 MB 2.4 MB/s eta 0:00:11
   -------------- ------------------------- 14.9/41.0 MB 2.3 MB/s eta 0:00:12
   --------------- ------------------------ 15.5/41.0 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 15.7/41.0 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 16.0/41.0 MB 2.3 MB/s eta 0:00:11
   ---------------- ----------------------- 16.5/41.0 MB 2.3 MB/s eta 0:00:11
   ---------------- ----------------------- 17.0/41.0 MB 2.3 MB/s eta 0:00:11
   ----------------- ---------------------- 17.6/41.0 MB 2.3 MB/s eta 0:00:11
   ----------------- ---------------------- 18.1/41.0 MB 2.3 MB/s eta 0:00:11
   ------------------ --------------------- 18.9/41.0 MB 2.3 MB/s eta 0:00:10
   ------------------ --------------------- 19.1/41.0 MB 2.3 MB/s eta 0:00:10
   ------------------- -------------------- 19.7/41.0 MB 2.3 MB/s eta 0:00:10
   ------------------- -------------------- 20.2/41.0 MB 2.3 MB/s eta 0:00:10
   ------------------- -------------------- 20.4/41.0 MB 2.3 MB/s eta 0:00:10
   -------------------- ------------------- 20.7/41.0 MB 2.3 MB/s eta 0:00:09
   -------------------- ------------------- 21.5/41.0 MB 2.3 MB/s eta 0:00:09
   --------------------- ------------------ 21.8/41.0 MB 2.3 MB/s eta 0:00:09
   --------------------- ------------------ 22.3/41.0 MB 2.3 MB/s eta 0:00:09
   ---------------------- ----------------- 22.5/41.0 MB 2.3 MB/s eta 0:00:09
   ---------------------- ----------------- 23.3/41.0 MB 2.3 MB/s eta 0:00:08
   ----------------------- ---------------- 23.9/41.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 24.6/41.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 24.9/41.0 MB 2.3 MB/s eta 0:00:08
   ------------------------ --------------- 25.4/41.0 MB 2.3 MB/s eta 0:00:07
   ------------------------- -------------- 26.2/41.0 MB 2.3 MB/s eta 0:00:07
   -------------------------- ------------- 26.7/41.0 MB 2.3 MB/s eta 0:00:07
   -------------------------- ------------- 27.5/41.0 MB 2.4 MB/s eta 0:00:06
   --------------------------- ------------ 28.0/41.0 MB 2.4 MB/s eta 0:00:06
   ---------------------------- ----------- 28.8/41.0 MB 2.4 MB/s eta 0:00:06
   ---------------------------- ----------- 29.6/41.0 MB 2.4 MB/s eta 0:00:05
   ----------------------------- ---------- 30.1/41.0 MB 2.4 MB/s eta 0:00:05
   ----------------------------- ---------- 30.7/41.0 MB 2.4 MB/s eta 0:00:05
   ------------------------------ --------- 31.5/41.0 MB 2.4 MB/s eta 0:00:04
   ------------------------------- -------- 32.2/41.0 MB 2.4 MB/s eta 0:00:04
   ------------------------------- -------- 32.8/41.0 MB 2.5 MB/s eta 0:00:04
   -------------------------------- ------- 33.3/41.0 MB 2.5 MB/s eta 0:00:04
   --------------------------------- ------ 34.1/41.0 MB 2.5 MB/s eta 0:00:03
   ---------------------------------- ----- 34.9/41.0 MB 2.5 MB/s eta 0:00:03
   ---------------------------------- ----- 35.4/41.0 MB 2.5 MB/s eta 0:00:03
   ----------------------------------- ---- 36.4/41.0 MB 2.5 MB/s eta 0:00:02
   ------------------------------------ --- 37.2/41.0 MB 2.5 MB/s eta 0:00:02
   ------------------------------------- -- 38.0/41.0 MB 2.6 MB/s eta 0:00:02
   ------------------------------------- -- 38.8/41.0 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 39.6/41.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  40.4/41.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  40.9/41.0 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 41.0/41.0 MB 2.6 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.6.0

  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /packages/0d/76/77cf2ac1f2a9cc00c073d49e1e16244e389dd88e2490c91d84e1e3e4d126/scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
#Import the scikit-learn library for training and testing data splitting.
from sklearn.model_selection import train_test_split
#X_train is the input value used for training the Model.
#X_test is the input data used to test the trained model.
#y_train is the output value used for training the Model.
#y_test is the output data used to test the trained model.
#The data split ratio is 70% for training and 30% for testing. If random_state is set to 0, the testing data is selected randomly but reproducibly.
X_train,X_test,y_train,y_test=train_test_split(inputVal,outputVal,test_size=0.30,random_state=0)

In [13]:
#Imports the LinearRegression class from the linear_model module of the scikit-learn library.
from sklearn.linear_model import LinearRegression
#It allows you to create and train a linear regression model.
regressor=LinearRegression()
#To train (or fit) a machine-learning model on a given dataset.
regressor.fit(X_train,y_train)

LinearRegression()

In [15]:
#To make predictions on new or unseen data after the model has been trained using the fit() method.
y_pred=regressor.predict(X_test)

In [16]:
#Imports the r2_score class from the metrics module of the scikit-learn library.
from sklearn.metrics import r2_score
#To validate the test data using the R² (R-squared) evaluation metric in scikit-learn library
r=r2_score(y_test,y_pred)
r

0.9740993407213511

In [28]:
#pickle module in Python is used to save and load the data
import pickle
# Save the training data to a file
pickle.dump(regressor,open("resultModel.sav",'wb'))