In [1]:
#importing the Library
#Pandas - For data manipulation & analysis.
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
#pandas.get_dummies() is a super handy function in pandas that converts categorical variables into one-hot encoded (binary) variables.
#drop_first=True: Drops the first category to avoid multicollinearity (used in regression).
#Use .astype() to explicitly set the data type of the resulting dummy variables — for example, converting from default uint8 to int, float, or bool
datasets=pd.get_dummies(dataset,drop_first=True).astype(int)

In [5]:
datasets.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [6]:
datasets.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=datasets[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=datasets[['charges']]

In [8]:
#Import the scikit-learn library for training and testing data splitting.
from sklearn.model_selection import train_test_split
#X_train is the input value used for training the Model.
#X_test is the input data used to test the trained model.
#y_train is the output value used for training the Model.
#y_test is the output data used to test the trained model.
#The data split ratio is 70% for training and 30% for testing. If random_state is set to 0, the testing data is selected randomly but reproducibly.
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [10]:
ada_regressor1 = AdaBoostRegressor(
    estimator=RandomForestRegressor(max_depth=3),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)
ada_regressor1.fit(X_train,y_train)

C:\Users\YUVARAJ.R\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(estimator=RandomForestRegressor(max_depth=3),
                  learning_rate=0.5, n_estimators=100, random_state=42)

In [11]:
ada_regressor2 = AdaBoostRegressor(
    estimator=DecisionTreeRegressor(max_depth=3),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)
ada_regressor2.fit(X_train,y_train)

C:\Users\YUVARAJ.R\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=3),
                  learning_rate=0.5, n_estimators=100, random_state=42)

In [12]:
ada_regressor3 = AdaBoostRegressor(
    estimator=SVR(),
    n_estimators=100,
    learning_rate=0.5,
    random_state=42
)
ada_regressor3.fit(X_train,y_train)

C:\Users\YUVARAJ.R\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(estimator=SVR(), learning_rate=0.5, n_estimators=100,
                  random_state=42)

In [13]:
y_pred1 = ada_regressor1.predict(X_test)
y_pred2 = ada_regressor2.predict(X_test)
y_pred3 = ada_regressor3.predict(X_test)

In [14]:
#Imports the r2_score class from the metrics module of the scikit-learn library.
from sklearn.metrics import r2_score
#To validate the test data using the R² (R-squared) evaluation metric in scikit-learn library
RandomForestRegressor=r2_score(y_test,y_pred1)
RandomForestRegressor

0.8646280131001621

In [15]:
#To validate the test data using the R² (R-squared) evaluation metric in scikit-learn library
DecisionTreeRegressor=r2_score(y_test,y_pred2)
DecisionTreeRegressor

0.8616571366968581

In [16]:
#To validate the test data using the R² (R-squared) evaluation metric in scikit-learn library
SVR=r2_score(y_test,y_pred2)
SVR

0.8616571366968581

In [18]:
#pickle module in Python is used to save and load the data
import pickle
# Save the training data to a file
pickle.dump(ada_regressor1,open("ADABoost_model.sav","wb"))
model=pickle.load(open("ADABoost_model.sav","rb"))
#Load the saved model file in read mode to predict the user input.
result=model.predict([[50,31,0,1,0]])
#Print the response / result.
result

AttributeError: 'float' object has no attribute 'predict'